[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment-specific configurations
[environments.production.variables]
NODE_ENV = "production"